version: '3.5'

services:
  opcua-server-1:
    hostname: "opcua-server-1"
    build:
      context: opcua-server/
    command: ["demo_server.py","opc.tcp://0.0.0.0:4840/freeopcua/server/"]
    ports:
      - "4840:4840"
    networks:
      - elk
  opcua-server-2:
    hostname: "opcua-server-2"
    build:
      context: opcua-server/
    command: ["demo_server.py","opc.tcp://0.0.0.0:4841/freeopcua/server/"]
    ports:
      - "4841:4841"
    networks:
      - elk
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.3.0
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.3.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/plant-index-template.json:/usr/share/logstash/config/plant-index-template.json
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - opcua-server-1
      - opcua-server-2
      - elasticsearch
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.3.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    name: "elk"
    driver: bridge
# You need to increase max_map_count on your Docker host:
# $ sysctl -w vm.max_map_count=262144